cookie:
  expiry_days: 30
  key: "chave_secreta_do_cookie" # **Importante: Mude esta chave para uma string segura**
  name: "cookie_riv"
credentials:
  usernames:
    usuario1:
      email: "usuario1@exemplo.com"
      name: "Usu치rio Um"
      password: "@usu치rio1"
    usuario2:
      email: "usuario2@exemplo.com"
      name: "Usu치rio Dois"
      password: "@usu치rio2"